TRAIN:
  BATCH_SIZE: 36
  NUM_EPOCHS: 100
  LAMBDA: 0.5
  TH_HIGH: 0.65
  TH_LOW: 0.4
  LR: 1e-3
  SCHEDULER_GAMMA: 0.96

MODEL:
  ANCHOR_MIN_SIZES: [65, 99, 115, 145, 185, 215]
  ANCHOR_MAX_SIZES: [85, 110, 135, 175, 200, 230]
