TRAIN:
  BATCH_SIZE: 36
  NUM_EPOCHS: 200
  LAMBDA: 1.0
  TH_HIGH: 0.6
  TH_LOW: 0.3
  LR: 1e-3
  SCHEDULER_GAMMA: 0.96

MODEL:
  ANCHOR_MIN_SIZES: [50, 99, 115, 145, 185, 215]
  ANCHOR_MAX_SIZES: [80, 115, 135, 175, 200, 230]
