MODEL:
  NET: "SiamConcatRPN"

  Z_SIZE: 300
  X_SIZE: 300

  ANCHOR_MIN_SIZES: [55, 75, 105, 135, 165, 200]
  ANCHOR_MAX_SIZES: [65, 90, 115, 150, 185, 220]

TRAIN:
  LR: 1e-3
  BATCH_SIZE: 22

  USE_MASK: True
  CROP_CONTEXT_AMOUNT_Z: 1.5
  CROP_CONTEXT_AMOUNT_X: 1.5

  LAMBDA: 2.0

  DATA_AUG_TRANSLATE_RANGE: 0.3
  DATA_AUG_RESIZE_SCALE_MIN: 0.35
  DATA_AUG_RESIZE_SCALE_MAX: 1.5
