MODEL:
  NET: "SiamBroadcastRPN"

  Z_SIZE: 129
  X_SIZE: 257

  ANCHOR_MIN_SIZES: [50, 65]
  ANCHOR_MAX_SIZES: [60, 75]

  FEATURE_MAPS_DIM: [17, 9]
  FEATURE_MAPS_STRIDES: [16, 32]
  ANCHOR_ASPECT_RATIOS: [[2, 3], [2, 3]]

TRAIN:
  LR: 0.75e-3
  BATCH_SIZE: 16
  NUM_EPOCHS: 1000

  CROP_CONTEXT_AMOUNT_Z: 0.1
  CROP_CONTEXT_AMOUNT_X: 2.0

  TH_HIGH: 0.50
  TH_LOW: 0.25

  LAMBDA: 1.5

  FRAME_RANGE: 50

  DATA_AUG_TRANSLATE_RANGE: 0.3
  DATA_AUG_RESIZE_SCALE_MIN: 0.75
  DATA_AUG_RESIZE_SCALE_MAX: 1.25
